FROM nginx

RUN rm /etc/nginx/conf.d/*

COPY ./conf/configuration.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]



# docker compose down frontend && docker rmi ft_transcendence-frontend && docker compose build frontend && docker compose up frontend