version: '3.9'

services:
  django:
    build: ./backend/conf/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    depends_on:
      - database
    networks:
      my_net:
        ipv4_address: 178.18.0.20
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      my_net:
        ipv4_address: 178.18.0.21
  frontend:
    build: ./frontend/conf/
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/code
    depends_on:
      - django
    networks:
      my_net:
        ipv4_address: 178.18.0.22
networks:
  my_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 178.18.0.0/16