# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
RUN apt-get update && apt-get install -y curl
RUN mkdir /code
WORKDIR /code
# Copy the local directory contents into the container at /usr/src/app
COPY ../ /code

# Optional: Install any needed packages specified in requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV PORT 8080

# Run python -m http.server when the container launches
CMD ["python", "-m", "http.server", "8080", "--bind", "0.0.0.0"]